version: "2"
containers:
- name: cloud-client
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
  ports:
  - 80
aws_accounts:
- name: ZT_AWS
  managed_policies:
  - arn:aws:iam::aws:policy/AdministratorAccess
azure_subscriptions:
- name: ZT_AZ
  roles:
  - Contributor
