#!/bin/bash

TF_VERSION=1.0.11
TF_PLATFORM=linux_amd64
TF_URL=https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_${TF_PLATFORM}.zip
TF_DOWNLOAD=terraform_${TF_VERSION}_${TF_PLATFORM}.zip


install_tf() {
  set-workdir /tmp
  wget ${TF_URL}
  unzip ${TF_DOWNLOAD}
  mv terraform /usr/local/bin/
}

install_tf
get_aws_vpc_repo() {
  set-workdir ~/
  git clone https://github.com/thegoatrodeo/aws-vpc
  set-workdir ~/aws-vpc
}
get_aws_vpc_repo
